// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EventResultPublic = {
    id: string;
    event_id: string;
    player_id: string;
    score: number;
    tiebreaker_rank: number;
    final_rank?: (number | null);
};

export type EventResultsPublic = {
    data: Array<EventResultPublic>;
    count: number;
};

export type EventResultsWithPlayersPublic = {
    data: Array<EventResultWithPlayer>;
    count: number;
};

export type EventResultUpdate = {
    score?: (number | null);
    tiebreaker_rank?: (number | null);
};

export type EventResultWithPlayer = {
    id: string;
    event_id: string;
    player_id: string;
    player_display_name: string;
    player_slug?: (string | null);
    score: number;
    tiebreaker_rank: number;
    final_rank?: (number | null);
};

export type EventStatus = 'pending' | 'approved';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
};

export type OrganizationPublic = {
    name: string;
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    id: string;
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
};

export type ParsedResultRow = {
    player_name: string;
    country: string;
    score: number;
    tiebreaker_rank: number;
};

export type ParsedResultWithCandidates = {
    row: ParsedResultRow;
    candidates: Array<PlayerSearchResult>;
};

export type ParseResultsRequest = {
    rows: Array<ParsedResultRow>;
};

export type ParseResultsResponse = {
    results: Array<ParsedResultWithCandidates>;
};

export type PlayerCreate = {
    display_name: string;
    country?: (string | null);
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
};

export type PlayerHistory = {
    data: Array<PlayerResultWithEvent>;
};

export type PlayerPublic = {
    display_name: string;
    country?: (string | null);
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
    id: string;
    slug?: (string | null);
    created_at?: (string | null);
};

export type PlayerResultWithEvent = {
    result_id: string;
    event_id: string;
    event_name: string;
    start_date: string;
    end_date: string;
    score: number;
    tiebreaker_rank: number;
    final_rank?: (number | null);
};

export type PlayerSearchResult = {
    player: PlayerPublic;
    similarity: number;
};

export type PlayerSearchResults = {
    data: Array<PlayerSearchResult>;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerUpdate = {
    display_name?: (string | null);
    country?: (string | null);
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
    slug?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuizEventCreate = {
    name: string;
    start_date: string;
    end_date: string;
    description?: (string | null);
    organizer_name: string;
    format?: ({
    [key: string]: unknown;
} | null);
    series_id?: (string | null);
    organization_id?: (string | null);
};

export type QuizEventPublic = {
    name: string;
    start_date: string;
    end_date: string;
    description?: (string | null);
    organizer_name: string;
    id: string;
    status: EventStatus;
    submitted_by_id: string;
    series_id?: (string | null);
    organization_id?: (string | null);
    format?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type QuizEventsPublic = {
    data: Array<QuizEventPublic>;
    count: number;
};

export type QuizEventUpdate = {
    name?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    description?: (string | null);
    organizer_name?: (string | null);
    format?: ({
    [key: string]: unknown;
} | null);
    series_id?: (string | null);
    organization_id?: (string | null);
};

export type QuizSeriesCreate = {
    name: string;
    description?: (string | null);
    organization_id?: (string | null);
};

export type QuizSeriesListPublic = {
    data: Array<QuizSeriesPublic>;
    count: number;
};

export type QuizSeriesPublic = {
    name: string;
    description?: (string | null);
    id: string;
    organization_id?: (string | null);
};

export type QuizSeriesUpdate = {
    name?: (string | null);
    description?: (string | null);
    organization_id?: (string | null);
};

export type ResolvedResultRow = {
    player_id?: (string | null);
    player_create?: (PlayerCreate | null);
    score: number;
    tiebreaker_rank: number;
};

export type SubmitMode = 'append' | 'replace';

export type SubmitResultsRequest = {
    results: Array<ResolvedResultRow>;
    mode?: SubmitMode;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type EventsReadEventsData = {
    limit?: number;
    seriesId?: (string | null);
    skip?: number;
    status?: (EventStatus | null);
};

export type EventsReadEventsResponse = (QuizEventsPublic);

export type EventsCreateEventData = {
    requestBody: QuizEventCreate;
};

export type EventsCreateEventResponse = (QuizEventPublic);

export type EventsReadEventData = {
    id: string;
};

export type EventsReadEventResponse = (QuizEventPublic);

export type EventsUpdateEventData = {
    id: string;
    requestBody: QuizEventUpdate;
};

export type EventsUpdateEventResponse = (QuizEventPublic);

export type EventsApproveEventData = {
    id: string;
};

export type EventsApproveEventResponse = (QuizEventPublic);

export type EventsReadEventResultsData = {
    id: string;
};

export type EventsReadEventResultsResponse = (EventResultsPublic);

export type EventsSubmitResultsData = {
    id: string;
    requestBody: SubmitResultsRequest;
};

export type EventsSubmitResultsResponse = (EventResultsPublic);

export type EventsReadEventResultsWithPlayersData = {
    id: string;
};

export type EventsReadEventResultsWithPlayersResponse = (EventResultsWithPlayersPublic);

export type EventsParseResultsData = {
    id: string;
    requestBody: ParseResultsRequest;
};

export type EventsParseResultsResponse = (ParseResultsResponse);

export type EventsDeleteEventResultData = {
    id: string;
    resultId: string;
};

export type EventsDeleteEventResultResponse = ({
    [key: string]: (string);
});

export type EventsUpdateEventResultData = {
    eventId: string;
    requestBody: EventResultUpdate;
    resultId: string;
};

export type EventsUpdateEventResultResponse = (EventResultPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    id: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    id: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type PlayersSearchPlayersRouteData = {
    country?: (string | null);
    limit?: number;
    q: string;
};

export type PlayersSearchPlayersRouteResponse = (PlayerSearchResults);

export type PlayersGetPlayerBySlugRouteData = {
    slug: string;
};

export type PlayersGetPlayerBySlugRouteResponse = (PlayerPublic);

export type PlayersGetPlayerHistoryRouteData = {
    playerId: string;
};

export type PlayersGetPlayerHistoryRouteResponse = (PlayerHistory);

export type PlayersGetPlayerData = {
    playerId: string;
};

export type PlayersGetPlayerResponse = (PlayerPublic);

export type PlayersUpdatePlayerRouteData = {
    playerId: string;
    requestBody: PlayerUpdate;
};

export type PlayersUpdatePlayerRouteResponse = (PlayerPublic);

export type PlayersListPlayersData = {
    limit?: number;
    skip?: number;
};

export type PlayersListPlayersResponse = (PlayersPublic);

export type PlayersCreatePlayerRouteData = {
    requestBody: PlayerCreate;
};

export type PlayersCreatePlayerRouteResponse = (PlayerPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SeriesReadSeriesData = {
    limit?: number;
    skip?: number;
};

export type SeriesReadSeriesResponse = (QuizSeriesListPublic);

export type SeriesCreateSeriesData = {
    requestBody: QuizSeriesCreate;
};

export type SeriesCreateSeriesResponse = (QuizSeriesPublic);

export type SeriesReadSeriesItemData = {
    id: string;
};

export type SeriesReadSeriesItemResponse = (QuizSeriesPublic);

export type SeriesUpdateSeriesData = {
    id: string;
    requestBody: QuizSeriesUpdate;
};

export type SeriesUpdateSeriesResponse = (QuizSeriesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);