// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompetitionCreate = {
    name: string;
    description?: (string | null);
    organization_id: string;
};

export type CompetitionListPublic = {
    data: Array<CompetitionPublic>;
    count: number;
};

export type CompetitionPublic = {
    name: string;
    description?: (string | null);
    id: string;
    slug: string;
    organization_id: string;
    organization_name?: (string | null);
    organization_slug?: (string | null);
};

export type CompetitionUpdate = {
    name?: (string | null);
    description?: (string | null);
    organization_id?: (string | null);
    slug?: (string | null);
};

export type EventCreate = {
    name: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    is_online?: boolean;
    venue?: (string | null);
    city?: (string | null);
    country?: (string | null);
    organization_id: string;
};

export type EventListPublic = {
    data: Array<EventPublic>;
    count: number;
};

export type EventPublic = {
    name: string;
    description?: (string | null);
    start_date: string;
    end_date: string;
    is_online?: boolean;
    venue?: (string | null);
    city?: (string | null);
    country?: (string | null);
    id: string;
    slug: string;
    organization_id: string;
    organization_name?: (string | null);
    organization_slug?: (string | null);
    quiz_count?: number;
};

export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_online?: (boolean | null);
    venue?: (string | null);
    city?: (string | null);
    country?: (string | null);
    organization_id?: (string | null);
    slug?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MergeConflict = {
    quiz_id: string;
    quiz_name: string;
    start_date: string;
    source_score: number;
    source_rank: (number | null);
    target_score: number;
    target_rank: (number | null);
    kind?: string;
};

export type MergePlayersPreview = {
    moved_results_count: number;
    conflicts: Array<MergeConflict>;
    filled_fields: Array<(string)>;
    added_countries: Array<(string)>;
};

export type MergePlayersRequest = {
    source_player_id: string;
    target_player_id: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
};

export type OrganizationPublic = {
    name: string;
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    id: string;
    slug: string;
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    description?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    slug?: (string | null);
};

export type ParsedResultRow = {
    player_name: string;
    country: string;
    score: number;
};

export type ParsedResultWithCandidates = {
    row: ParsedResultRow;
    candidates: Array<PlayerSearchResult>;
};

export type ParseResultsRequest = {
    rows: Array<ParsedResultRow>;
};

export type ParseResultsResponse = {
    results: Array<ParsedResultWithCandidates>;
};

export type PlayerCompetitionGroup = {
    competition_id: (string | null);
    competition_name: (string | null);
    competition_slug: (string | null);
    results: Array<PlayerResultWithQuiz>;
    total_count: number;
};

export type PlayerCompetitionHistory = {
    data: Array<PlayerResultWithQuiz>;
    count: number;
    competition_name?: (string | null);
};

export type PlayerCreate = {
    display_name: string;
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
    countries?: Array<(string)>;
};

export type PlayerHistoryGrouped = {
    data: Array<PlayerCompetitionGroup>;
    total_quizzes: number;
    wins: number;
    podiums: number;
};

export type PlayerMergeAuditPublic = {
    id: string;
    merged_at: (string | null);
    performed_by_email: string;
    source_player_id: string;
    source_display_name: string;
    source_slug: (string | null);
    target_player_id: string;
    target_display_name: string;
    moved_results_count: number;
    deleted_conflicts_count: number;
};

export type PlayerMergeAuditsPublic = {
    data: Array<PlayerMergeAuditPublic>;
    count: number;
};

export type PlayerPublic = {
    display_name: string;
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
    id: string;
    slug?: (string | null);
    is_published?: boolean;
    created_at?: (string | null);
    countries?: Array<(string)>;
};

export type PlayerResultWithQuiz = {
    result_id: string;
    quiz_id: string;
    quiz_name: string;
    quiz_slug?: (string | null);
    start_date: string;
    end_date: string;
    score: number;
    final_rank?: (number | null);
    country?: (string | null);
    competition_id?: (string | null);
    competition_name?: (string | null);
    partners?: Array<ResultPartner>;
};

export type PlayerSearchBatchRequest = {
    names: Array<(string)>;
};

export type PlayerSearchBatchResponse = {
    results: {
        [key: string]: Array<PlayerSearchResult>;
    };
};

export type PlayerSearchResult = {
    player: PlayerPublic;
    similarity: number;
};

export type PlayerSearchResults = {
    data: Array<PlayerSearchResult>;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerUpdate = {
    display_name?: (string | null);
    country?: (string | null);
    countries?: (Array<(string)> | null);
    city?: (string | null);
    club?: (string | null);
    bio?: (string | null);
    photo_url?: (string | null);
    slug?: (string | null);
};

export type PodiumFinisher = {
    place: number;
    score: number;
    participants?: Array<ResultParticipantPublic>;
};

export type PodiumPublic = {
    quizzes: Array<QuizPodium>;
    standings: Array<PodiumStanding>;
};

export type PodiumStanding = {
    player_id: string;
    player_display_name: string;
    player_slug?: (string | null);
    gold: number;
    silver: number;
    bronze: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuizCreate = {
    name: string;
    start_date: string;
    end_date: string;
    description?: (string | null);
    organizer_name?: (string | null);
    participant_mode?: QuizParticipantMode;
    format_id?: (string | null);
    competition_id?: (string | null);
    event_id?: (string | null);
    organization_id?: (string | null);
};

export type QuizFormatCreate = {
    name: string;
    description?: (string | null);
    rounds?: Array<(string)>;
    per_round_stats_eligible?: boolean;
};

export type QuizFormatPublic = {
    name: string;
    description?: (string | null);
    rounds?: Array<(string)>;
    per_round_stats_eligible?: boolean;
    id: string;
};

export type QuizFormatsPublic = {
    data: Array<QuizFormatPublic>;
    count: number;
};

export type QuizFormatUpdate = {
    name?: (string | null);
    description?: (string | null);
    rounds?: (Array<(string)> | null);
    per_round_stats_eligible?: (boolean | null);
};

export type QuizParticipantMode = 'individual' | 'pairs';

export type QuizPodium = {
    quiz_id: string;
    quiz_name: string;
    quiz_slug?: (string | null);
    start_date: string;
    end_date: string;
    finishers: Array<PodiumFinisher>;
};

export type QuizPublic = {
    name: string;
    start_date: string;
    end_date: string;
    description?: (string | null);
    organizer_name?: (string | null);
    participant_mode?: QuizParticipantMode;
    id: string;
    slug: string;
    status: QuizStatus;
    submitted_by_id: string;
    competition_id?: (string | null);
    event_id?: (string | null);
    event_name?: (string | null);
    event_slug?: (string | null);
    organization_id?: (string | null);
    format_id?: (string | null);
    format?: (QuizFormatPublic | null);
    created_at?: (string | null);
};

export type QuizResultPublic = {
    id: string;
    quiz_id: string;
    score: number;
    final_rank?: (number | null);
    round_scores?: (Array<(number | null)> | null);
    participants?: Array<ResultParticipantPublic>;
};

export type QuizResultsPublic = {
    data: Array<QuizResultPublic>;
    count: number;
};

export type QuizResultsWithPlayersPublic = {
    data: Array<QuizResultWithPlayer>;
    count: number;
};

export type QuizResultUpdate = {
    final_rank?: (number | null);
    score?: (number | null);
    round_scores?: (Array<(number | null)> | null);
    country?: (string | null);
    participants?: (Array<ResultParticipantCreate> | null);
};

export type QuizResultWithPlayer = {
    id: string;
    quiz_id: string;
    score: number;
    final_rank?: (number | null);
    round_scores?: (Array<(number | null)> | null);
    participants?: Array<ResultParticipantPublic>;
};

export type QuizStatus = 'pending' | 'approved' | 'rejected';

export type QuizUpdate = {
    name?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    description?: (string | null);
    organizer_name?: (string | null);
    format_id?: (string | null);
    competition_id?: (string | null);
    event_id?: (string | null);
    organization_id?: (string | null);
    slug?: (string | null);
    participant_mode?: (QuizParticipantMode | null);
};

export type QuizzesPublic = {
    data: Array<QuizPublic>;
    count: number;
};

export type ResolvedResultRow = {
    final_rank: number;
    score?: (number | null);
    round_scores?: (Array<(number | null)> | null);
    participants: Array<ResultParticipant>;
};

/**
 * One member of a result, as submitted by the upload wizard.
 */
export type ResultParticipant = {
    player_id?: (string | null);
    player_create?: (PlayerCreate | null);
    country?: (string | null);
};

/**
 * One member of a result, after players have been resolved to ids.
 */
export type ResultParticipantCreate = {
    player_id: string;
    country?: (string | null);
};

export type ResultParticipantPublic = {
    slot: number;
    player_id: string;
    player_display_name: string;
    player_slug?: (string | null);
    country?: (string | null);
};

export type ResultPartner = {
    player_id: string;
    display_name: string;
    slug?: (string | null);
};

export type SubmitMode = 'append' | 'replace';

export type SubmitResultsRequest = {
    results: Array<ResolvedResultRow>;
    mode?: SubmitMode;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserMePublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    db_target?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_organizer?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CompetitionsReadCompetitionsData = {
    limit?: number;
    skip?: number;
};

export type CompetitionsReadCompetitionsResponse = (CompetitionListPublic);

export type CompetitionsCreateCompetitionData = {
    requestBody: CompetitionCreate;
};

export type CompetitionsCreateCompetitionResponse = (CompetitionPublic);

export type CompetitionsReadCompetitionData = {
    id: string;
};

export type CompetitionsReadCompetitionResponse = (CompetitionPublic);

export type CompetitionsUpdateCompetitionData = {
    id: string;
    requestBody: CompetitionUpdate;
};

export type CompetitionsUpdateCompetitionResponse = (CompetitionPublic);

export type CompetitionsDeleteCompetitionData = {
    id: string;
};

export type CompetitionsDeleteCompetitionResponse = ({
    [key: string]: (boolean);
});

export type CompetitionsReadCompetitionPodiumData = {
    id: string;
};

export type CompetitionsReadCompetitionPodiumResponse = (PodiumPublic);

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = (EventListPublic);

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadEventData = {
    id: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    id: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsDeleteEventData = {
    id: string;
};

export type EventsDeleteEventResponse = ({
    [key: string]: (boolean);
});

export type EventsReadEventPodiumData = {
    id: string;
};

export type EventsReadEventPodiumResponse = (PodiumPublic);

export type FormatsReadFormatsData = {
    limit?: number;
    skip?: number;
};

export type FormatsReadFormatsResponse = (QuizFormatsPublic);

export type FormatsCreateFormatData = {
    requestBody: QuizFormatCreate;
};

export type FormatsCreateFormatResponse = (QuizFormatPublic);

export type FormatsReadFormatData = {
    id: string;
};

export type FormatsReadFormatResponse = (QuizFormatPublic);

export type FormatsUpdateFormatData = {
    id: string;
    requestBody: QuizFormatUpdate;
};

export type FormatsUpdateFormatResponse = (QuizFormatPublic);

export type FormatsDeleteFormatData = {
    id: string;
};

export type FormatsDeleteFormatResponse = ({
    [key: string]: (boolean);
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    id: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    id: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    id: string;
};

export type OrganizationsDeleteOrganizationResponse = ({
    [key: string]: (boolean);
});

export type PlayersSearchPlayersRouteData = {
    country?: (string | null);
    limit?: number;
    q?: string;
};

export type PlayersSearchPlayersRouteResponse = (PlayerSearchResults);

export type PlayersSearchPlayersBatchRouteData = {
    requestBody: PlayerSearchBatchRequest;
};

export type PlayersSearchPlayersBatchRouteResponse = (PlayerSearchBatchResponse);

export type PlayersListPlayerMergesRouteData = {
    limit?: number;
    skip?: number;
};

export type PlayersListPlayerMergesRouteResponse = (PlayerMergeAuditsPublic);

export type PlayersPreviewMergePlayersRouteData = {
    requestBody: MergePlayersRequest;
};

export type PlayersPreviewMergePlayersRouteResponse = (MergePlayersPreview);

export type PlayersMergePlayersRouteData = {
    requestBody: MergePlayersRequest;
};

export type PlayersMergePlayersRouteResponse = (PlayerPublic);

export type PlayersGetPlayerBySlugRouteData = {
    slug: string;
};

export type PlayersGetPlayerBySlugRouteResponse = (PlayerPublic);

export type PlayersGetPlayerHistoryRouteData = {
    playerId: string;
};

export type PlayersGetPlayerHistoryRouteResponse = (PlayerHistoryGrouped);

export type PlayersGetPlayerCompetitionHistoryRouteData = {
    competition?: (string | null);
    limit?: number;
    playerId: string;
    skip?: number;
};

export type PlayersGetPlayerCompetitionHistoryRouteResponse = (PlayerCompetitionHistory);

export type PlayersGetPlayerData = {
    playerId: string;
};

export type PlayersGetPlayerResponse = (PlayerPublic);

export type PlayersUpdatePlayerRouteData = {
    playerId: string;
    requestBody: PlayerUpdate;
};

export type PlayersUpdatePlayerRouteResponse = (PlayerPublic);

export type PlayersDeletePlayerRouteData = {
    playerId: string;
};

export type PlayersDeletePlayerRouteResponse = ({
    [key: string]: (string);
});

export type PlayersListPlayersData = {
    limit?: number;
    skip?: number;
};

export type PlayersListPlayersResponse = (PlayersPublic);

export type PlayersCreatePlayerRouteData = {
    requestBody: PlayerCreate;
};

export type PlayersCreatePlayerRouteResponse = (PlayerPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuizzesReadQuizzesData = {
    competitionId?: (string | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
    status?: (QuizStatus | null);
};

export type QuizzesReadQuizzesResponse = (QuizzesPublic);

export type QuizzesCreateQuizData = {
    requestBody: QuizCreate;
};

export type QuizzesCreateQuizResponse = (QuizPublic);

export type QuizzesReadQuizData = {
    id: string;
};

export type QuizzesReadQuizResponse = (QuizPublic);

export type QuizzesUpdateQuizData = {
    id: string;
    requestBody: QuizUpdate;
};

export type QuizzesUpdateQuizResponse = (QuizPublic);

export type QuizzesDeleteQuizData = {
    id: string;
};

export type QuizzesDeleteQuizResponse = ({
    [key: string]: (string);
});

export type QuizzesApproveQuizData = {
    id: string;
};

export type QuizzesApproveQuizResponse = (QuizPublic);

export type QuizzesRejectQuizData = {
    id: string;
};

export type QuizzesRejectQuizResponse = (QuizPublic);

export type QuizzesSetQuizPendingData = {
    id: string;
};

export type QuizzesSetQuizPendingResponse = (QuizPublic);

export type QuizzesReadQuizResultsData = {
    id: string;
};

export type QuizzesReadQuizResultsResponse = (QuizResultsPublic);

export type QuizzesSubmitResultsData = {
    id: string;
    requestBody: SubmitResultsRequest;
};

export type QuizzesSubmitResultsResponse = (QuizResultsPublic);

export type QuizzesReadQuizResultsWithPlayersData = {
    id: string;
};

export type QuizzesReadQuizResultsWithPlayersResponse = (QuizResultsWithPlayersPublic);

export type QuizzesParseResultsData = {
    id: string;
    requestBody: ParseResultsRequest;
};

export type QuizzesParseResultsResponse = (ParseResultsResponse);

export type QuizzesDeleteQuizResultData = {
    id: string;
    resultId: string;
};

export type QuizzesDeleteQuizResultResponse = ({
    [key: string]: (string);
});

export type QuizzesUpdateQuizResultData = {
    quizId: string;
    requestBody: QuizResultUpdate;
    resultId: string;
};

export type QuizzesUpdateQuizResultResponse = (QuizResultPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserMePublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);