"""add unique constraint event_id player_id on eventresult

Revision ID: 5461017c4a57
Revises: 5da9e038d366
Create Date: 2026-05-26 09:44:24.769540

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5461017c4a57'
down_revision = '5da9e038d366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'eventresult', ['event_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventresult', type_='unique')
    # ### end Alembic commands ###
