"""add quizformat table and round columns

Revision ID: b89ea95603f2
Revises: b7c9d2e4f1a3
Create Date: 2026-06-11 22:33:15.997261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b89ea95603f2'
down_revision = 'b7c9d2e4f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizformat',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rounds', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('eventresult', sa.Column('round_1', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_2', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_3', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_4', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_5', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_6', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_7', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_8', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_9', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_10', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_11', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_12', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_13', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_14', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_15', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_16', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_17', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_18', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_19', sa.Float(), nullable=True))
    op.add_column('eventresult', sa.Column('round_20', sa.Float(), nullable=True))
    op.add_column('quizevent', sa.Column('format_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'quizevent', 'quizformat', ['format_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quizevent', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizevent', sa.Column('format', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizevent', type_='foreignkey')
    op.drop_column('quizevent', 'format_id')
    op.drop_column('eventresult', 'round_20')
    op.drop_column('eventresult', 'round_19')
    op.drop_column('eventresult', 'round_18')
    op.drop_column('eventresult', 'round_17')
    op.drop_column('eventresult', 'round_16')
    op.drop_column('eventresult', 'round_15')
    op.drop_column('eventresult', 'round_14')
    op.drop_column('eventresult', 'round_13')
    op.drop_column('eventresult', 'round_12')
    op.drop_column('eventresult', 'round_11')
    op.drop_column('eventresult', 'round_10')
    op.drop_column('eventresult', 'round_9')
    op.drop_column('eventresult', 'round_8')
    op.drop_column('eventresult', 'round_7')
    op.drop_column('eventresult', 'round_6')
    op.drop_column('eventresult', 'round_5')
    op.drop_column('eventresult', 'round_4')
    op.drop_column('eventresult', 'round_3')
    op.drop_column('eventresult', 'round_2')
    op.drop_column('eventresult', 'round_1')
    op.drop_table('quizformat')
    # ### end Alembic commands ###
