"""add event table and quiz event_id

Revision ID: bbf23bc9abe0
Revises: b4c8e1f7a2d9
Create Date: 2026-08-19 16:03:46.619775

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'bbf23bc9abe0'
down_revision = 'b4c8e1f7a2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_slug'), 'event', ['slug'], unique=True)
    op.add_column('quiz', sa.Column('event_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'quiz_event_id_fkey', 'quiz', 'event', ['event_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_event_id_fkey', 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'event_id')
    op.drop_index(op.f('ix_event_slug'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
