"""add_is_published_to_player

Revision ID: f25a043bf66a
Revises: d7d5076c786b
Create Date: 2026-06-04 18:03:26.531624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f25a043bf66a'
down_revision = 'd7d5076c786b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_published')
    # ### end Alembic commands ###
