/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as PublicQuizzesRouteImport } from './routes/_public/quizzes'
import { Route as PublicPlayersRouteImport } from './routes/_public/players'
import { Route as PublicOrganizationsRouteImport } from './routes/_public/organizations'
import { Route as PublicCompetitionsRouteImport } from './routes/_public/competitions'
import { Route as LayoutUploadRouteImport } from './routes/_layout/upload'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as PublicQuizzesSlugRouteImport } from './routes/_public/quizzes_.$slug'
import { Route as PublicPlayersSlugRouteImport } from './routes/_public/players_.$slug'
import { Route as PublicOrganizationsSlugRouteImport } from './routes/_public/organizations_.$slug'
import { Route as PublicCompetitionsSlugRouteImport } from './routes/_public/competitions_.$slug'
import { Route as LayoutAdminQuizzesRouteImport } from './routes/_layout/admin_.quizzes'
import { Route as LayoutAdminOrganizationsRouteImport } from './routes/_layout/admin_.organizations'
import { Route as LayoutAdminFormatsRouteImport } from './routes/_layout/admin_.formats'
import { Route as LayoutAdminCompetitionsRouteImport } from './routes/_layout/admin_.competitions'
import { Route as LayoutAdminQuizzesIdRouteImport } from './routes/_layout/admin_.quizzes_.$id'
import { Route as LayoutAdminPlayersMergesRouteImport } from './routes/_layout/admin_.players.merges'
import { Route as LayoutAdminPlayersMergeRouteImport } from './routes/_layout/admin_.players.merge'
import { Route as PublicPlayersSlugCompetitionsCompetitionSlugRouteImport } from './routes/_public/players_.$slug_.competitions.$competitionSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const PublicQuizzesRoute = PublicQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlayersRoute = PublicPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOrganizationsRoute = PublicOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompetitionsRoute = PublicCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => PublicRoute,
} as any)
const LayoutUploadRoute = LayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const PublicQuizzesSlugRoute = PublicQuizzesSlugRouteImport.update({
  id: '/quizzes_/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlayersSlugRoute = PublicPlayersSlugRouteImport.update({
  id: '/players_/$slug',
  path: '/players/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOrganizationsSlugRoute = PublicOrganizationsSlugRouteImport.update({
  id: '/organizations_/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompetitionsSlugRoute = PublicCompetitionsSlugRouteImport.update({
  id: '/competitions_/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const LayoutAdminQuizzesRoute = LayoutAdminQuizzesRouteImport.update({
  id: '/admin_/quizzes',
  path: '/admin/quizzes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminOrganizationsRoute =
  LayoutAdminOrganizationsRouteImport.update({
    id: '/admin_/organizations',
    path: '/admin/organizations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminFormatsRoute = LayoutAdminFormatsRouteImport.update({
  id: '/admin_/formats',
  path: '/admin/formats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminCompetitionsRoute = LayoutAdminCompetitionsRouteImport.update({
  id: '/admin_/competitions',
  path: '/admin/competitions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminQuizzesIdRoute = LayoutAdminQuizzesIdRouteImport.update({
  id: '/admin_/quizzes_/$id',
  path: '/admin/quizzes/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPlayersMergesRoute =
  LayoutAdminPlayersMergesRouteImport.update({
    id: '/admin_/players/merges',
    path: '/admin/players/merges',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminPlayersMergeRoute = LayoutAdminPlayersMergeRouteImport.update({
  id: '/admin_/players/merge',
  path: '/admin/players/merge',
  getParentRoute: () => LayoutRoute,
} as any)
const PublicPlayersSlugCompetitionsCompetitionSlugRoute =
  PublicPlayersSlugCompetitionsCompetitionSlugRouteImport.update({
    id: '/players_/$slug_/competitions/$competitionSlug',
    path: '/players/$slug/competitions/$competitionSlug',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/competitions': typeof PublicCompetitionsRoute
  '/organizations': typeof PublicOrganizationsRoute
  '/players': typeof PublicPlayersRoute
  '/quizzes': typeof PublicQuizzesRoute
  '/admin/competitions': typeof LayoutAdminCompetitionsRoute
  '/admin/formats': typeof LayoutAdminFormatsRoute
  '/admin/organizations': typeof LayoutAdminOrganizationsRoute
  '/admin/quizzes': typeof LayoutAdminQuizzesRoute
  '/competitions/$slug': typeof PublicCompetitionsSlugRoute
  '/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/players/$slug': typeof PublicPlayersSlugRoute
  '/quizzes/$slug': typeof PublicQuizzesSlugRoute
  '/admin/players/merge': typeof LayoutAdminPlayersMergeRoute
  '/admin/players/merges': typeof LayoutAdminPlayersMergesRoute
  '/admin/quizzes/$id': typeof LayoutAdminQuizzesIdRoute
  '/players/$slug/competitions/$competitionSlug': typeof PublicPlayersSlugCompetitionsCompetitionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/competitions': typeof PublicCompetitionsRoute
  '/organizations': typeof PublicOrganizationsRoute
  '/players': typeof PublicPlayersRoute
  '/quizzes': typeof PublicQuizzesRoute
  '/admin/competitions': typeof LayoutAdminCompetitionsRoute
  '/admin/formats': typeof LayoutAdminFormatsRoute
  '/admin/organizations': typeof LayoutAdminOrganizationsRoute
  '/admin/quizzes': typeof LayoutAdminQuizzesRoute
  '/competitions/$slug': typeof PublicCompetitionsSlugRoute
  '/organizations/$slug': typeof PublicOrganizationsSlugRoute
  '/players/$slug': typeof PublicPlayersSlugRoute
  '/quizzes/$slug': typeof PublicQuizzesSlugRoute
  '/admin/players/merge': typeof LayoutAdminPlayersMergeRoute
  '/admin/players/merges': typeof LayoutAdminPlayersMergesRoute
  '/admin/quizzes/$id': typeof LayoutAdminQuizzesIdRoute
  '/players/$slug/competitions/$competitionSlug': typeof PublicPlayersSlugCompetitionsCompetitionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/upload': typeof LayoutUploadRoute
  '/_public/competitions': typeof PublicCompetitionsRoute
  '/_public/organizations': typeof PublicOrganizationsRoute
  '/_public/players': typeof PublicPlayersRoute
  '/_public/quizzes': typeof PublicQuizzesRoute
  '/_home/': typeof HomeIndexRoute
  '/_layout/admin_/competitions': typeof LayoutAdminCompetitionsRoute
  '/_layout/admin_/formats': typeof LayoutAdminFormatsRoute
  '/_layout/admin_/organizations': typeof LayoutAdminOrganizationsRoute
  '/_layout/admin_/quizzes': typeof LayoutAdminQuizzesRoute
  '/_public/competitions_/$slug': typeof PublicCompetitionsSlugRoute
  '/_public/organizations_/$slug': typeof PublicOrganizationsSlugRoute
  '/_public/players_/$slug': typeof PublicPlayersSlugRoute
  '/_public/quizzes_/$slug': typeof PublicQuizzesSlugRoute
  '/_layout/admin_/players/merge': typeof LayoutAdminPlayersMergeRoute
  '/_layout/admin_/players/merges': typeof LayoutAdminPlayersMergesRoute
  '/_layout/admin_/quizzes_/$id': typeof LayoutAdminQuizzesIdRoute
  '/_public/players_/$slug_/competitions/$competitionSlug': typeof PublicPlayersSlugCompetitionsCompetitionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/upload'
    | '/competitions'
    | '/organizations'
    | '/players'
    | '/quizzes'
    | '/admin/competitions'
    | '/admin/formats'
    | '/admin/organizations'
    | '/admin/quizzes'
    | '/competitions/$slug'
    | '/organizations/$slug'
    | '/players/$slug'
    | '/quizzes/$slug'
    | '/admin/players/merge'
    | '/admin/players/merges'
    | '/admin/quizzes/$id'
    | '/players/$slug/competitions/$competitionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/upload'
    | '/competitions'
    | '/organizations'
    | '/players'
    | '/quizzes'
    | '/admin/competitions'
    | '/admin/formats'
    | '/admin/organizations'
    | '/admin/quizzes'
    | '/competitions/$slug'
    | '/organizations/$slug'
    | '/players/$slug'
    | '/quizzes/$slug'
    | '/admin/players/merge'
    | '/admin/players/merges'
    | '/admin/quizzes/$id'
    | '/players/$slug/competitions/$competitionSlug'
  id:
    | '__root__'
    | '/_home'
    | '/_layout'
    | '/_public'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/upload'
    | '/_public/competitions'
    | '/_public/organizations'
    | '/_public/players'
    | '/_public/quizzes'
    | '/_home/'
    | '/_layout/admin_/competitions'
    | '/_layout/admin_/formats'
    | '/_layout/admin_/organizations'
    | '/_layout/admin_/quizzes'
    | '/_public/competitions_/$slug'
    | '/_public/organizations_/$slug'
    | '/_public/players_/$slug'
    | '/_public/quizzes_/$slug'
    | '/_layout/admin_/players/merge'
    | '/_layout/admin_/players/merges'
    | '/_layout/admin_/quizzes_/$id'
    | '/_public/players_/$slug_/competitions/$competitionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_public/quizzes': {
      id: '/_public/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof PublicQuizzesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/players': {
      id: '/_public/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PublicPlayersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/organizations': {
      id: '/_public/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof PublicOrganizationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/competitions': {
      id: '/_public/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof PublicCompetitionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_public/quizzes_/$slug': {
      id: '/_public/quizzes_/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof PublicQuizzesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/players_/$slug': {
      id: '/_public/players_/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PublicPlayersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/organizations_/$slug': {
      id: '/_public/organizations_/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof PublicOrganizationsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/competitions_/$slug': {
      id: '/_public/competitions_/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof PublicCompetitionsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_layout/admin_/quizzes': {
      id: '/_layout/admin_/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof LayoutAdminQuizzesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/organizations': {
      id: '/_layout/admin_/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof LayoutAdminOrganizationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/formats': {
      id: '/_layout/admin_/formats'
      path: '/admin/formats'
      fullPath: '/admin/formats'
      preLoaderRoute: typeof LayoutAdminFormatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/competitions': {
      id: '/_layout/admin_/competitions'
      path: '/admin/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof LayoutAdminCompetitionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/quizzes_/$id': {
      id: '/_layout/admin_/quizzes_/$id'
      path: '/admin/quizzes/$id'
      fullPath: '/admin/quizzes/$id'
      preLoaderRoute: typeof LayoutAdminQuizzesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/players/merges': {
      id: '/_layout/admin_/players/merges'
      path: '/admin/players/merges'
      fullPath: '/admin/players/merges'
      preLoaderRoute: typeof LayoutAdminPlayersMergesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin_/players/merge': {
      id: '/_layout/admin_/players/merge'
      path: '/admin/players/merge'
      fullPath: '/admin/players/merge'
      preLoaderRoute: typeof LayoutAdminPlayersMergeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_public/players_/$slug_/competitions/$competitionSlug': {
      id: '/_public/players_/$slug_/competitions/$competitionSlug'
      path: '/players/$slug/competitions/$competitionSlug'
      fullPath: '/players/$slug/competitions/$competitionSlug'
      preLoaderRoute: typeof PublicPlayersSlugCompetitionsCompetitionSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
  LayoutAdminCompetitionsRoute: typeof LayoutAdminCompetitionsRoute
  LayoutAdminFormatsRoute: typeof LayoutAdminFormatsRoute
  LayoutAdminOrganizationsRoute: typeof LayoutAdminOrganizationsRoute
  LayoutAdminQuizzesRoute: typeof LayoutAdminQuizzesRoute
  LayoutAdminPlayersMergeRoute: typeof LayoutAdminPlayersMergeRoute
  LayoutAdminPlayersMergesRoute: typeof LayoutAdminPlayersMergesRoute
  LayoutAdminQuizzesIdRoute: typeof LayoutAdminQuizzesIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUploadRoute: LayoutUploadRoute,
  LayoutAdminCompetitionsRoute: LayoutAdminCompetitionsRoute,
  LayoutAdminFormatsRoute: LayoutAdminFormatsRoute,
  LayoutAdminOrganizationsRoute: LayoutAdminOrganizationsRoute,
  LayoutAdminQuizzesRoute: LayoutAdminQuizzesRoute,
  LayoutAdminPlayersMergeRoute: LayoutAdminPlayersMergeRoute,
  LayoutAdminPlayersMergesRoute: LayoutAdminPlayersMergesRoute,
  LayoutAdminQuizzesIdRoute: LayoutAdminQuizzesIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PublicRouteChildren {
  PublicCompetitionsRoute: typeof PublicCompetitionsRoute
  PublicOrganizationsRoute: typeof PublicOrganizationsRoute
  PublicPlayersRoute: typeof PublicPlayersRoute
  PublicQuizzesRoute: typeof PublicQuizzesRoute
  PublicCompetitionsSlugRoute: typeof PublicCompetitionsSlugRoute
  PublicOrganizationsSlugRoute: typeof PublicOrganizationsSlugRoute
  PublicPlayersSlugRoute: typeof PublicPlayersSlugRoute
  PublicQuizzesSlugRoute: typeof PublicQuizzesSlugRoute
  PublicPlayersSlugCompetitionsCompetitionSlugRoute: typeof PublicPlayersSlugCompetitionsCompetitionSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCompetitionsRoute: PublicCompetitionsRoute,
  PublicOrganizationsRoute: PublicOrganizationsRoute,
  PublicPlayersRoute: PublicPlayersRoute,
  PublicQuizzesRoute: PublicQuizzesRoute,
  PublicCompetitionsSlugRoute: PublicCompetitionsSlugRoute,
  PublicOrganizationsSlugRoute: PublicOrganizationsSlugRoute,
  PublicPlayersSlugRoute: PublicPlayersSlugRoute,
  PublicQuizzesSlugRoute: PublicQuizzesSlugRoute,
  PublicPlayersSlugCompetitionsCompetitionSlugRoute:
    PublicPlayersSlugCompetitionsCompetitionSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
