export const Labels = {
  adminQuizzesPageHeading: "admin-quizzes-page-heading",
  resultDeleteButton: "result-delete-button",
  uploadModeNew: "upload-mode-new",
  uploadModeExisting: "upload-mode-existing",
  uploadModeToggleNew: "upload-mode-toggle-new",
  uploadModeToggleExisting: "upload-mode-toggle-existing",
  uploadExistingQuizSelect: "upload-existing-quiz-select",
  submitModeToggle: "submit-mode-toggle",
  columnMappingPosition: "column-mapping-position",
  homeGreeting: "home-greeting",
  homeRecentQuizzes: "home-recent-quizzes",
  homeRecentPlayers: "home-recent-players",
  homeAdminLoginLink: "home-admin-login-link",
} as const
